name: UiPath CI/CD Sample

on:
  push:
    branches:
      - dev

jobs:
  analyze-project:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout repository
        uses: Mikael-RnD/setup-uipath@v1 # Or the official UiPath action if available
        with:
          version: 'latest' # Or a specific version like '2.0.17'
